function [net,tot] = flux(bz,difx,dify)
    net = difx*dify*sum(sum(bz(3:end-2,3:end-2)));
    tot = difx*dify*sum(sum(abs(bz(3:end-2,3:end-2))));
    %left and right
        net = net + 0.5*difx*dify*sum(bz(3:end-2,2) +...
            bz(3:end-2,end-1));
        tot = tot + 0.5*difx*dify*sum(abs(bz(3:end-2,2)) +...
            abs(bz(3:end-2,end-1)));
    %top and bottom
        net = net + 0.5*difx*dify*sum(bz(2,3:end-2) +...
            bz(end-1,3:end-2));
        tot = tot + 0.5*difx*dify*sum(abs(bz(2,3:end-2)) +...
            abs(bz(end-1,3:end-2)));
    %corners
        net = net + 0.25*difx*dify*(bz(2,2) +...
            bz(2,end-1) + bz(end-1,2) + bz(end-1,end-1));
        tot = tot + 0.25*difx*dify*(abs(bz(2,2)) +...
            abs(bz(2,end-1)) + abs(bz(end-1,2)) +...
            abs(bz(end-1,end-1)));
end